name: botyim
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modal_progress_hud: ^0.1.3
  flutter_dialogflow: ^0.1.3
  edge_alert: ^0.0.1
  on_boarding_ui: ^0.0.4
  bubble: ^1.1.9+1
  carousel_slider: ^2.2.1
  flutter_launcher_icons: ^0.8.1
  video_player: ^0.10.1+3
  chewie: ^0.9.7
  google_maps_flutter: ^0.5.27+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_form_builder: ^3.12.0
  flushbar: ^1.10.4
  intl: ^0.16.1
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.7
  flutter_redux: ^0.6.0
  firebase_core: ^0.4.5

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/Icon3.png"
  image_path_ios: "assets/images/Icon3.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: false # can specify file name here e.g. "My-Launcher-Icon"
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/botyim-sawcua-cee03868b9dc.json
   - assets/bot.png
   - assets/user.png
   - assets/images/read1.gif
   - assets/images/read2.gif
   - assets/images/read3.gif
   - assets/images/logo.jpg
   - assets/video/branch.mp4
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - assets: assets/fonts/OpenSans.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    # - family: Itim
    #    fonts:
    #      - asset: fonts/Itim
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
    # - family: Lobster
    #    fonts:
    #      - asset: fonts/Lobster
    # - family: Prompt
    #    fonts:
    #      - asset: fonts/Prompt
    # - family: Ranchers
    #    fonts:
    #      - asset: fonts/Ranchers
    # - family: Taviraj
    #    fonts:
    #      - asset: fonts/Taviraj
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
